import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@rainbow-me/rainbowkit/styles.css";
import { Provider } from "./provider";

import NavLinks from "@/app/components/header"
import FootLinks from "@/app/components/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <Provider>
        <NavLinks />
          {children}

          <FootLinks />
        </Provider>
      </body>
    </html>
  );
}
